import { IFieldData } from 'mole-ui';

export const mockData = {
  type: 'CONDITION',
  key: 'mz9LnKvIRXr6qNLCZcaME',
  operator: 'and',
  showName: '并且',
  children: [
    {
      type: 'REGULAR',
      key: '87H7rJ3Thn3ViDrIa5gOu',
      rule: {
        column: '',
        operator: '',
        showName: '',
        dataType: '',
        value: null,
        valueType: 'field',
      },
    },
    {
      type: 'REGULAR',
      key: 'X3xAO-waMrKG56_5kvAiF',
      rule: {
        column: '',
        operator: '',
        showName: '',
        dataType: '',
        value: null,
        valueType: 'field',
      },
    },
    {
      type: 'REGULAR',
      key: 'qsVuEZV44XLm_PBPImkqX',
      rule: {
        column: '',
        operator: '',
        showName: '',
        dataType: '',
        value: null,
        valueType: 'field',
      },
    },
    {
      type: 'REGULAR',
      key: 'aU1GnxR2AYNnbKptcHcgY',
      rule: {
        column: '',
        operator: '',
        showName: '',
        dataType: '',
        value: null,
        valueType: 'field',
      },
    },
    {
      type: 'CONDITION',
      key: 'VO-dmtK1jzZilerre12dR',
      operator: 'and',
      showName: '并且',
      children: [
        {
          type: 'REGULAR',
          key: 'PJ5L9L1GoRvca-E7FOm6w',
          rule: {
            column: '',
            operator: '',
            showName: '',
            dataType: '',
            value: null,
            valueType: 'field',
          },
        },
        {
          type: 'REGULAR',
          key: 'vbmsX6Z3lC-iJf8aREUY9',
          rule: {
            column: '',
            operator: '',
            showName: '',
            dataType: '',
            value: null,
            valueType: 'field',
          },
        },
        {
          type: 'REGULAR',
          key: 'TT64XmcCi75Nmy7fH551q',
          rule: {
            column: '',
            operator: '',
            showName: '',
            dataType: '',
            value: null,
            valueType: 'field',
          },
        },
      ],
    },
    {
      type: 'CONDITION',
      key: 'T5vUmniNCGQaFMbxq-H8s',
      operator: 'and',
      showName: '并且',
      children: [
        {
          type: 'REGULAR',
          key: 'PJ5L9L1GoRvca-E7FOm6w',
          rule: {
            column: '',
            operator: '',
            showName: '',
            dataType: '',
            value: null,
            valueType: 'field',
          },
        },
        {
          type: 'REGULAR',
          key: 'TT64XmcCi75Nmy7fH551q',
          rule: {
            column: '',
            operator: '',
            showName: '',
            dataType: '',
            value: null,
            valueType: 'field',
          },
        },
      ],
    },
  ],
};

export const ideFieldDataList = [
  {
    id: 3978964314112304,
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'aa',
    type: 1,
    fieldDisplayName: '文本',
    modelName: 'simple_data',
    modelId: 3978966349496624,
    attributeName: 'aa',
    primary: false,
    fieldDataType: 'string',
    properties: {
      controlId: 'field_1',
      dataTypeShowName: '文本',
      viewType: 'Text',
    },
    maxLength: 100,
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    required: true,
    unique: false,
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
    enable: true,
  },
  {
    id: 3978964358644016,
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'bb',
    type: 1,
    fieldDisplayName: '整数',
    modelName: 'simple_data',
    modelId: 3978966349496624,
    attributeName: 'bb',
    primary: false,
    fieldDataType: 'long',
    properties: {
      controlId: 'field_2',
      dataTypeShowName: '整数',
      viewType: 'Long',
    },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    required: false,
    unique: false,
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
    enable: true,
  },
  {
    id: 39789616,
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'bb_1',
    type: 1,
    fieldDisplayName: '整数范围',
    modelName: 'simple_data',
    modelId: 3978966349496624,
    attributeName: 'bb-1',
    primary: false,
    fieldDataType: 'range<long>',
    properties: {
      controlId: 'field_2_1',
      dataTypeShowName: '整数范围',
      viewType: 'Long',
    },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    required: false,
    unique: false,
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
    enable: true,
  },
  {
    id: 39789644780,
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'cc',
    type: 1,
    fieldDisplayName: '浮点数',
    modelName: 'simple_data',
    modelId: 3978966349496624,
    attributeName: 'cc',
    primary: false,
    fieldDataType: 'double',
    properties: {
      controlId: 'field_3',
      dataTypeShowName: '浮点数',
      viewType: 'Number',
    },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    required: false,
    unique: false,
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
    enable: true,
  },
  {
    id: 39785445480,
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'cc_1',
    type: 1,
    fieldDisplayName: '浮点数范围',
    modelName: 'simple_data',
    modelId: 3978966349496624,
    attributeName: 'cc-1',
    primary: false,
    fieldDataType: 'range<double>',
    properties: {
      controlId: 'field_3_1',
      dataTypeShowName: '浮点数范围',
      viewType: 'Number',
    },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    required: false,
    unique: false,
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
    enable: true,
  },
  {
    id: 3978969836,
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'dd',
    type: 1,
    fieldDisplayName: '日期时间',
    modelName: 'simple_data',
    modelId: 3978966349496624,
    attributeName: 'dd',
    primary: false,
    fieldDataType: 'datetime',
    properties: {
      controlId: 'field_4',
      dataTypeShowName: '日期时间',
      viewType: 'Date',
    },
    format: 'YYYY/MM/DD',
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    required: false,
    unique: false,
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
    enable: true,
  },
  {
    id: 39789646,
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'dd_1',
    type: 1,
    fieldDisplayName: '日期时间范围',
    modelName: 'simple_data',
    modelId: 3978966349496624,
    attributeName: 'dd-1',
    primary: false,
    fieldDataType: 'range<datetime>',
    properties: {
      controlId: 'field_4_1',
      dataTypeShowName: '日期时间范围',
      viewType: 'Date',
    },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    required: false,
    unique: false,
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
    enable: true,
  },
  {
    id: 3978942,
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'ee_1',
    type: 1,
    fieldDisplayName: '富文本',
    modelName: 'simple_data',
    modelId: 3978966349496624,
    attributeName: 'ee-1',
    primary: false,
    fieldDataType: 'richtext',
    properties: {
      controlId: 'field_5_1',
      dataTypeShowName: '富文本',
      viewType: '',
    },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    defaultValue: '外部链接',
    required: false,
    unique: false,
    percentage: false,
    sysCodeType: 1,
    sysSubDataType: 'APP_TYPE',
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
    enable: true,
  },
  {
    id: 3978964568097072,
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'ee',
    type: 1,
    fieldDisplayName: '系统编码',
    modelName: 'simple_data',
    modelId: 3978966349496624,
    attributeName: 'ee',
    primary: false,
    fieldDataType: 'syscode',
    properties: {
      controlId: 'field_5',
      dataTypeShowName: '单选',
      viewType: 'SystemCode',
    },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    defaultValue: [{ code: '03', name: '外部链接' }],
    required: false,
    unique: false,
    percentage: false,
    sysCodeType: 1,
    sysSubDataType: 'APP_TYPE',
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
    enable: true,
  },
  {
    id: 3978964610531632,
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'ff',
    type: 1,
    fieldDisplayName: '多选',
    modelName: 'simple_data',
    modelId: 3978966349496624,
    attributeName: 'ff',
    primary: false,
    fieldDataType: 'set<syscode>',
    properties: {
      controlId: 'field_6',
      dataTypeShowName: '多选',
      viewType: 'SystemCode',
    },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    defaultValue: [
      { code: 'DEPARTMENT_CATEGORY_001', name: '职能部门' },
      { code: 'DEPARTMENT_CATEGORY_002', name: '车间' },
    ],
    required: false,
    unique: false,
    percentage: false,
    sysCodeType: 1,
    sysSubDataType: 'DEPARTMENT_CATEGORY',
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
    enable: true,
  },
  {
    id: 3978964660404528,
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'ddd',
    type: 1,
    fieldDisplayName: '布尔',
    modelName: 'simple_data',
    modelId: 3978966349496624,
    attributeName: 'ddd',
    primary: false,
    fieldDataType: 'boolean',
    properties: {
      controlId: 'field_7',
      dataTypeShowName: '布尔',
      viewType: 'Switch',
    },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    required: false,
    unique: false,
    percentage: false,
    switchEnableMessage: '开开开',
    switchDisableMessage: '关关关',
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
    enable: true,
  },
  {
    id: 3998413363233072,
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'ghgh',
    type: 1,
    fieldDisplayName: '关联模型',
    modelName: 'simple_data',
    modelId: 3978966349496624,
    attributeName: 'ghgh',
    primary: false,
    fieldDataType: 'linkmodel',
    properties: {
      controlId: 'advance_4',
      dataTypeShowName: '关联模型',
      viewType: 'Connect',
    },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    required: false,
    unique: false,
    linkModelName: 'simple_data',
    linkFieldName: 'ghgh',
    linkShowFieldName: 'aa',
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
    enable: true,
    showField: {
      id: 3978964314112304,
      appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
      name: 'aa',
      type: 1,
      fieldDisplayName: '文本',
      modelName: 'simple_data',
      modelId: 3978966349496624,
      attributeName: 'aa',
      primary: false,
      fieldDataType: 'string',
      properties: {
        controlId: 'field_1',
        dataTypeShowName: '文本',
        viewType: 'Text',
      },
      maxLength: 100,
      multiOptions: false,
      readOnly: false,
      multiLine: false,
      hasDefaultValue: false,
      required: false,
      unique: false,
      percentage: false,
      fileSizeMax: 0,
      fileNumberMax: 0,
      currentUser: false,
      currentDepart: false,
      decimalPlaces: 0,
      enable: true,
    },
  },
  {
    id: 4010372851679536,
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'zizizi',
    type: 1,
    fieldDisplayName: '自编码单选',
    modelName: 'simple_data',
    modelId: 3978966349496624,
    attributeName: 'zizizi',
    primary: false,
    fieldDataType: 'syscode',
    properties: {
      controlId: 'field_5',
      dataTypeShowName: '单选',
      viewType: 'SystemCode',
    },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    defaultValue: [{ code: 'a1', name: 'a1' }],
    required: false,
    unique: false,
    percentage: false,
    sysCodeType: 0,
    sysSubDataType: '_abc',
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
    enable: true,
  },
  {
    id: 4018254309671216,
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'fhfhfhfh222',
    type: 1,
    fieldDisplayName: '多选222',
    modelName: 'simple_data',
    modelId: 3978966349496624,
    attributeName: 'fhfhfhfh222',
    primary: false,
    fieldDataType: 'set<syscode>',
    properties: {
      controlId: 'field_6',
      dataTypeShowName: '多选',
      viewType: 'SystemCode',
    },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    required: false,
    unique: false,
    percentage: false,
    sysCodeType: 1,
    sysSubDataType: 'SCREEN_TYPE',
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
    enable: true,
  },
  {
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'id',
    type: 0,
    fieldDisplayName: '编号',
    modelName: 'simple_data',
    primary: false,
    fieldDataType: 'double',
    properties: { fieldDisplayName: '编号', dataType: 'double' },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
  },
  {
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'creator_id',
    type: 0,
    fieldDisplayName: '创建者',
    modelName: 'simple_data',
    primary: false,
    fieldDataType: 'sysuser',
    properties: { fieldDisplayName: '创建者', dataType: 'sysuser' },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
  },
  {
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'created_time',
    type: 0,
    fieldDisplayName: '创建时间',
    modelName: 'simple_data',
    primary: false,
    fieldDataType: 'systime',
    properties: {
      fieldDisplayName: '创建时间',
      dataType: 'systime',
      format: 'YYYY/MM/DD HH:mm:ss',
    },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
  },
  {
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'last_modified_time',
    type: 0,
    fieldDisplayName: '修改时间',
    modelName: 'simple_data',
    primary: false,
    fieldDataType: 'systime',
    properties: {
      fieldDisplayName: '修改时间',
      dataType: 'systime',
      format: 'YYYY/MM/DD HH:mm:ss',
    },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
  },
  {
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'last_modifier_id',
    type: 0,
    fieldDisplayName: '修改者',
    modelName: 'simple_data',
    primary: false,
    fieldDataType: 'sysuser',
    properties: { fieldDisplayName: '修改者', dataType: 'sysuser' },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
  },
  {
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'belong_company_code',
    type: 0,
    fieldDisplayName: '所属公司',
    modelName: 'simple_data',
    primary: false,
    fieldDataType: 'syscompany',
    properties: { fieldDisplayName: '所属公司', dataType: 'syscompany' },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
  },
  {
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'belong_dept_code',
    type: 0,
    fieldDisplayName: '所属部门',
    modelName: 'simple_data',
    primary: false,
    fieldDataType: 'sysdept',
    properties: { fieldDisplayName: '所属部门', dataType: 'sysdept' },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
  },
  {
    appId: 'App_dda84b3b23b8a5c4ebc72368c79b442d',
    fieldName: 'belong_owner_code',
    type: 0,
    fieldDisplayName: '所属人员',
    modelName: 'simple_data',
    primary: false,
    fieldDataType: 'sysstaff',
    properties: { fieldDisplayName: '所属人员', dataType: 'sysstaff' },
    multiOptions: false,
    readOnly: false,
    multiLine: false,
    hasDefaultValue: false,
    percentage: false,
    fileSizeMax: 0,
    fileNumberMax: 0,
    currentUser: false,
    currentDepart: false,
    decimalPlaces: 0,
  },
];

export const fieldDataList: IFieldData[] = ideFieldDataList.map(
  ({
    fieldName,
    fieldDisplayName,
    fieldDataType,
    required,
    readOnly,
    maxLength,
    multiOptions,
    ...extra
  }) => ({
    fieldName,
    fieldDisplayName,
    fieldDataType,
    required,
    componentProps: {
      readOnly,
      maxLength,
    },
    extra,
  }),
);
